// Shared host UI. Copies served by standalone examples are generated by build.mjs.
export function lang() {
  try {
    const value = new URLSearchParams(globalThis.location?.search).get('lang');
    if (value === 'zh' || value === 'en') return value;
  } catch {}
  try {
    const languages = globalThis.navigator?.languages ?? [globalThis.navigator?.language];
    if (languages.some(value => /^zh/i.test(value ?? ''))) return 'zh';
  } catch {}
  return 'en';
}

export function theme() {
  try {
    const value = new URLSearchParams(globalThis.location?.search).get('theme');
    if (value === 'light' || value === 'dark') return value;
  } catch {}
  try { if (globalThis.matchMedia?.('(prefers-color-scheme: dark)').matches) return 'dark'; } catch {}
  return 'light';
}

export function t(strings) { return strings[lang()]; }

// Translate only the host's initial markup, before original modules can add DOM.
// Text nodes are changed individually to preserve controls, whitespace and layout.
export function init(strings = []) {
  const language = lang();
  document.documentElement.lang = language;
  document.documentElement.dataset.theme = theme();
  const translations = new Map(strings.map(value => [value.en, value[language]]));
  const translate = value => {
    const key = value.trim();
    return translations.has(key) ? value.replace(key, translations.get(key)) : value;
  };
  const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_TEXT);
  while (walker.nextNode()) {
    const node = walker.currentNode;
    if (!node.parentElement.closest('script, style')) node.textContent = translate(node.textContent);
  }
  for (const node of document.querySelectorAll('[aria-label], [title], [placeholder]')) {
    for (const attribute of ['aria-label', 'title', 'placeholder']) {
      if (node.hasAttribute(attribute)) node.setAttribute(attribute, translate(node.getAttribute(attribute)));
    }
  }
  // Keep preferences when moving between the flight and model hosts.
  for (const link of document.querySelectorAll('a[href]')) {
    const url = new URL(link.href);
    if (url.origin === location.origin && /\.html$/.test(url.pathname)) {
      url.searchParams.set('lang', language);
      url.searchParams.set('theme', theme());
      link.href = url.href;
    }
  }
  for (const node of document.querySelectorAll('[data-console-en]')) {
    if (language === 'en') node.textContent = node.dataset.consoleEn;
  }
  mountFrame();
  document.documentElement.dataset.uiReady = 'true';
}

// Hosts annotate parameters, performance readouts and input hints. Moving the
// existing nodes preserves their ids, event handlers and original scene logic.
function mountFrame() {
  const picture = document.querySelector('[data-demo-picture]');
  if (!picture) return;
  const frame = document.createElement('main');
  frame.className = 'demo-frame-layout';
  const visual = document.createElement('div');
  visual.className = 'demo-visual';
  const stage = document.createElement('div');
  stage.className = 'demo-picture';
  const controls = document.createElement('section');
  controls.className = 'demo-controls';
  controls.dataset.demoConsole = '';
  const header = document.createElement('h2');
  header.className = 'demo-console-title';
  header.textContent = t({zh: '调试台', en: 'Console'});
  controls.setAttribute('aria-label', header.textContent);
  const parameters = document.createElement('div');
  parameters.className = 'demo-parameters';
  const performance = document.createElement('section');
  performance.className = 'demo-performance';
  performance.dataset.demoPerformance = '';
  const title = document.createElement('h3');
  title.textContent = t({zh: '性能', en: 'Performance'});
  performance.append(title);
  // Pull nested readouts out before moving their parameter group.
  for (const node of document.querySelectorAll('[data-demo-readout]')) performance.append(node);
  for (const hint of document.querySelectorAll('[data-demo-hint]')) {
    hint.removeAttribute('data-demo-control');
    hint.title = hint.textContent.trim();
    if (hint.dataset.hintKeys) {
      let keys = hint.dataset.hintKeys;
      if (lang() === 'zh') for (const [en, zh] of Object.entries({
        'Drag': '拖动', 'Scroll': '滚轮', 'Hold / Release': '按住 / 松开',
        'Hold to cast': '按住施法', 'LMB': '左键', 'RMB': '右键',
      })) keys = keys.replaceAll(en, zh);
      hint.textContent = keys;
    }
    visual.append(hint);
  }
  for (const group of document.querySelectorAll('[data-demo-control]')) {
    if (!group.closest('[data-demo-performance]')) parameters.append(group);
  }
  // Associate separately authored labels with their input on the same row.
  for (const label of parameters.querySelectorAll('label[for]')) {
    const input = parameters.querySelector(`#${CSS.escape(label.htmlFor)}`);
    if (input && !label.contains(input)) label.append(input);
  }
  controls.append(header, parameters);
  if (performance.children.length > 1) controls.append(performance);
  stage.append(picture);
  visual.prepend(stage);
  frame.append(visual);
  if (parameters.children.length || performance.children.length > 1) frame.append(controls);
  else frame.classList.add('picture-only');
  document.body.prepend(frame);
  for (const node of [...document.body.children]) {
    if (node !== frame && node.tagName !== 'SCRIPT') node.remove();
  }
  document.documentElement.classList.add('demo-frame');
  picture.tabIndex = 0;
  stage.addEventListener('pointerdown', event => {
    const target = event.target.closest('canvas') || picture;
    target.tabIndex = 0;
    target.focus({preventScroll: true});
  }, {capture: true});
  const postHeight = () => {
    frame.style.setProperty('--picture-height', `${stage.getBoundingClientRect().height}px`);
    const height = Math.ceil(frame.getBoundingClientRect().height);
    if (window.parent !== window) parent.postMessage({type: 'gameref:frame-height', height}, '*');
  };
  const observer = new ResizeObserver(postHeight);
  observer.observe(stage);
  observer.observe(frame);
  window.addEventListener('load', postHeight);
  postHeight();
}
