import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const archiveRoot = fileURLToPath(new URL('.', import.meta.url));
export const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');

// All offsets refer to the frozen original, never to a progressively edited string.
export function localize(original, manifest) {
  assert.equal(original.length, manifest.original.bytes, 'Original byte count changed');
  assert.equal(sha256(original), manifest.original.sha256, 'Original hash changed');
  const parts = [];
  const applied = [];
  let cursor = 0;
  for (const patch of manifest.patches) {
    assert.equal(patch.expected_matches, 1);
    assert(patch.start >= cursor && patch.end > patch.start && patch.end <= original.length,
      `Invalid or overlapping range: ${patch.id}`);
    const before = original.subarray(patch.start, patch.end);
    assert.equal(sha256(before), patch.original_sha256, `Patch bytes changed: ${patch.id}`);
    assert.equal(original.indexOf(before), patch.start, `Patch first match: ${patch.id}`);
    assert.equal(original.indexOf(before, patch.start + 1), -1, `Patch must match once: ${patch.id}`);
    parts.push(original.subarray(cursor, patch.start), Buffer.from(patch.replacement));
    cursor = patch.end;
    applied.push({ id: patch.id, matches: 1 });
  }
  parts.push(original.subarray(cursor));
  return { bytes: Buffer.concat(parts), applied };
}

export function sliceSource(original, manifest) {
  const text = original.toString('utf8');
  const opening = '<script type="module">';
  const scriptStart = original.indexOf(opening);
  assert(scriptStart >= 0 && original.indexOf(opening, scriptStart + 1) === -1);
  const scriptEnd = original.indexOf('</script>', scriptStart);
  const markers = [...text.matchAll(/^\/\/ ([a-z]+\.js)\r?$/gm)].map(match => ({
    name: match[1], start: Buffer.byteLength(text.slice(0, match.index)),
  }));
  assert.equal(markers.length, 36, 'Expected exactly 36 module markers');
  assert.deepEqual(markers.map(m => m.name), manifest.modules.map(m => m.name));
  const slices = new Map([['src/_prelude.html', original.subarray(0, markers[0].start)]]);
  const rows = [];
  for (let i = 0; i < markers.length; i++) {
    const { name, start } = markers[i];
    const end = markers[i + 1]?.start ?? scriptEnd;
    assert(start > scriptStart && end <= scriptEnd);
    const bytes = original.subarray(start, end);
    const record = manifest.modules[i];
    assert.deepEqual([start, end, sha256(bytes)], [record.start, record.end, record.sha256], name);
    const line = 1 + original.subarray(0, start).toString().split('\n').length - 1;
    const lastLine = line + bytes.toString().split('\n').length - 1 - (bytes.at(-1) === 10 ? 1 : 0);
    const bundleLine = 1 + original.subarray(scriptStart, start).toString().split('\n').length - 1;
    assert.deepEqual([line, lastLine, bundleLine], [record.line_start, record.line_end, record.bundle_line_start]);
    slices.set(`src/${name}`, bytes);
    rows.push(`| [${name}](${name}) | ${line}–${lastLine} | ${bundleLine} | ${record.purpose} |`);
  }
  slices.set('src/_tail.html', original.subarray(scriptEnd));
  assert(Buffer.concat([...slices.values()]).equals(original), 'Full source reconstruction failed');
  slices.set('src/INDEX.md', Buffer.from([
    '# Antikythera bundle reading index', '',
    'Generated by `node antikythera/build.mjs`. These are byte-exact reading slices, not standalone ES modules. Imports and all HTML before the first marker remain in `_prelude.html`; `_tail.html` starts at the closing module-script tag.', '',
    'Concatenate `_prelude.html`, the 36 modules in the order below, and `_tail.html` to recover the entire original HTML. Module bytes alone recover the marker-delimited script region. Line ranges are 1-based in `original/antikythera.html`; bundle start lines count the opening module-script tag as line 1, matching the owner’s module-map.txt.', '',
    'Purposes follow the owner’s 2026-09-23 distillation README, §1.3. Helper modules not individually described there are identified from their original source.', '',
    '| Module | Original lines | Bundle start line | Purpose |',
    '|---|---|---|---|', ...rows, '',
  ].join('\n')));
  return slices;
}

export async function build(outputRoot = archiveRoot) {
  const manifest = JSON.parse(await readFile(path.join(archiveRoot, 'provenance/manifest.json'), 'utf8'));
  const original = await readFile(path.join(archiveRoot, manifest.original.path));
  const result = localize(original, manifest);
  assert.equal(sha256(result.bytes), manifest.public.sha256, 'Localized output hash changed');
  const outputs = sliceSource(original, manifest);
  outputs.set('public/index.html', result.bytes);
  for (const [relative, bytes] of outputs) {
    const target = path.join(outputRoot, relative);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, bytes);
  }
  return result.applied;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const applied = await build();
  console.log(`Built public/index.html and 36 source slices; ${applied.length} patches matched exactly once.`);
}
